inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

# private/protected は一段深くインデントする
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 168

Lint/SuppressedException:
  Exclude:
    - 'config/unicorn.conf.rb'
    - 'config/unicorn/production.rb'

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/unicorn.conf.rb'
    - 'config/deploy.rb'
    - 'config/unicorn/production.rb'

Lint/UriEscapeUnescape:
  Exclude:
    - 'app/models/post.rb'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'app/models/post.rb'

Metrics/BlockLength:
  Max: 113

Metrics/MethodLength:
  Max: 16

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'test/test_helper.rb'

# コメントは日本語でもok
Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

Style/CaseLikeIf:
  Exclude:
    - 'app/controllers/maps_controller.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/ClassMethods:
  Exclude:
    - 'app/models/user.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/maps_controller.rb'
    - 'app/controllers/password_resets_controller.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/GlobalVars:
  Exclude:
    - 'config/unicorn.conf.rb'
    - 'config/unicorn/production.rb'

Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/likes_controller.rb'
    - 'app/controllers/password_resets_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/static_pages_controller.rb'
    - 'app/models/post.rb'
    - 'app/models/user.rb'
    - 'db/migrate/20201019110941_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb'

Style/HashSyntax:
  Exclude:
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/picture_uploader.rb'
    - 'db/migrate/20200530081738_add_latitude_to_posts.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/account_activations_controller.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/static_pages_controller.rb'
    - 'app/models/post.rb'
    - 'app/models/user.rb'
    - 'db/migrate/20201019110941_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/MultilineTernaryOperator:
  Exclude:
    - 'app/models/user.rb'

Style/MutableConstant:
  Exclude:
    - 'app/models/user.rb'

Style/ParenthesesAroundCondition:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/picture_uploader.rb'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/RedundantFileExtensionInRequire:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/rails_helper.rb'

Style/RedundantRegexpEscape:
  Exclude:
    - 'config/initializers/carrier_wave.rb'

Style/RedundantSelf:
  Exclude:
    - 'app/models/post.rb'
    - 'app/models/user.rb'

Style/SafeNavigation:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/helpers/sessions_helper.rb'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/StringConcatenation:
  Exclude:
    -  'app/models/post.rb'
    -  'spec/models/user_spec.rb'

# ダブルクォートを使ってもok
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
