version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          - RAILS_ENV: test
          - RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

      - image: circleci/mysql:8.0.19
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'

    working_directory: ~/sample_app

    steps:
      - checkout # CI環境上の working_directory の値の場所にGitリポジトリをコピーする

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: mv config/database.yml.ci config/database.yml

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: bundle exec rake db:create

      - run: bundle exec rake db:schema:load

      - run: bundle exec rspec

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run: bundle exec rubocop

      - add_ssh_keys:
          fingerprints:
            - "ad:c0:d4:56:02:96:ae:6f:c6:7b:fa:61:88:02:21:b6"

      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy
