version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          RAILS_ENV: test
          DB_HOST: db
          DB_USERNAME: 'root'
          DB_PASSWORD: 'password'

      - image: circleci/mysql:8.0.19
        environment:
          MYSQL_DATABASE: 'Noodles_test'
          MYSQL_USER: 'root'
          MYSQL_ROOT_PASSWORD: 'password'

    working_directory: ~/sample_app

    steps:
      - checkout # CI環境上の working_directory の値の場所にGitリポジトリをコピーする

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Yarnをinstall
          command: yarn install --cache-folder ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: bundle exec rake db:create

      - run: bundle exec rake db:schema:load

      - run:
          name: execute rspec
          command: bundle exec rspec

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: run rubocop
          command: bundle exec rubocop
