development:
  adapter: mysql2
  encoding: utf8
  database: Noodles_development
  pool: 5
  username: root
  password: <%= Rails.application.credentials.db[:host] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: Noodles_test
  pool: 5
  username: root
  password: <%= Rails.application.credentials.db[:host] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: Noodles_production
  pool: 5
  username: ta93n
  password: 1234takumin
  host: <%= Rails.application.credentials.db[:host] %>
