development:
  adapter: mysql2
  encoding: utf8
  database: Noodles_development
  pool: 5
  username: root
  password: password
  host: db

test:
  adapter: mysql2
  encoding: utf8
  database: Noodles_test
  pool: 5
  username: root
  password: password
  host: db

production:
  adapter: mysql2
  encoding: utf8
  database: Noodles_production
  pool: 5
  username: ta93n
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>
