development:
  adapter: mysql2
  encoding: utf8
  database: Noodles_development
  pool: 5
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: Noodles_test
  pool: 5
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: Noodles_production
  pool: 5
  username: ta93n
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['RDS_ENDPOINT'] %>
